import type { BundleManifest } from "@/lib/bundle-engine";

export function renderInstallerPs1(manifest: BundleManifest, signature: string): string {
  const lines: string[] = [
    `#Requires -RunAsAdministrator`,
    `<#`,
    `  Bootstrap Hub Installer`,
    `  Bundle: ${escapePs1(manifest.name)}`,
    `  Created: ${manifest.createdAt}`,
    ``,
    `  If Windows blocks this script due to execution policy, either:`,
    `    - Run bootstrap.cmd as Administrator (recommended)`,
    `    - Run: powershell -ExecutionPolicy Bypass -File bootstrap.ps1`,
    `#>`,
    `param(`,
    `  [switch]$SkipSignatureCheck,`,
    `  [string]$LogPath = "$env:ProgramData\\BootstrapHub\\install.log"`,
    `)`,
    ``,
    `$ErrorActionPreference = "Stop"`,
    `$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path`,
    `$ManifestPath = Join-Path $ScriptDir "manifest.json"`,
    `$SignaturePath = Join-Path $ScriptDir "manifest.sig"`,
    `$ErrorLogPath = Join-Path (Split-Path $LogPath) "errors.log"`,
    ``,
    `function Write-Log {`,
    `  param([string]$Message)`,
    `  $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"`,
    `  $line = "[$ts] $Message"`,
    `  New-Item -ItemType Directory -Path (Split-Path $LogPath) -Force | Out-Null`,
    `  Add-Content -Path $LogPath -Value $line`,
    `  Write-Host $line`,
    `}`,
    ``,
    `function Write-ErrorLog {`,
    `  param([string]$Message)`,
    `  $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"`,
    `  $line = "[$ts] ERROR: $Message"`,
    `  New-Item -ItemType Directory -Path (Split-Path $ErrorLogPath) -Force | Out-Null`,
    `  Add-Content -Path $ErrorLogPath -Value $line`,
    `}`,
    ``,
    `function Test-Installed {`,
    `  param([hashtable]$App)`,
    `  $method = $App.detectionMethod`,
    `  $rule = $App.detectionRule`,
    `  # Idempotency marker written by a previous run`,
    `  $markerPath = "HKLM:\\Software\\BootstrapHub\\Installed"`,
    `  $marker = Get-ItemProperty -Path $markerPath -Name $App.id -ErrorAction SilentlyContinue`,
    `  if ($marker) { return $true }`,
    `  if ($method -eq "REGISTRY") {`,
    `    return Test-Path $rule.key`,
    `  }`,
    `  if ($method -eq "PROGRAM") {`,
    `    $name = $rule.displayNameContains`,
    `    $programs = Get-ItemProperty HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall*, HKLM:\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall*`,
    `    return ($programs | Where-Object { $_.DisplayName -like "*$name*" }) -ne $null`,
    `  }`,
    `  if ($method -eq "FILE") {`,
    `    $p = [System.Environment]::ExpandEnvironmentVariables($rule.path)`,
    `    return Test-Path $p`,
    `  }`,
    `  if ($method -eq "CUSTOM") {`,
    `    try { return Invoke-Expression $rule.script } catch { return $false }`,
    `  }`,
    `  return $false`,
    `}`,
    ``,
    `function Get-InstallerHash {`,
    `  param([string]$FilePath, [string]$ExpectedHash)`,
    `  if (-not $ExpectedHash) { return }`,
    `  $actual = (Get-FileHash -Path $FilePath -Algorithm SHA256).Hash`,
    `  if ($actual -ne $ExpectedHash) {`,
    `    throw "SHA256 mismatch for $FilePath (expected $ExpectedHash, got $actual)"`,
    `  }`,
    `  Write-Log "SHA256 verified: $FilePath"`,
    `}`,
    ``,
    `function Get-Installer {`,
    `  param([string]$Name, [string]$LocalFile, [string]$Url, [string]$ExpectedHash)`,
    `  if (Test-Path $LocalFile) {`,
    `    if ($ExpectedHash) { Get-InstallerHash -FilePath $LocalFile -ExpectedHash $ExpectedHash }`,
    `    return $LocalFile`,
    `  }`,
    `  if (-not $Url) { throw "No installer available for $Name" }`,
    `  $tmpDir = "$env:TEMP\\BootstrapHub\\files"`,
    `  New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null`,
    `  $ext = [System.IO.Path]::GetExtension($Url)`,
    `  if (-not $ext) { $ext = ".exe" }`,
    `  $dest = Join-Path $tmpDir ($Name.Replace(" ", "_") + $ext)`,
    `  Write-Log "Downloading $Name from $Url"`,
    `  Invoke-WebRequest -Uri $Url -OutFile $dest -UseBasicParsing`,
    `  if ($ExpectedHash) { Get-InstallerHash -FilePath $dest -ExpectedHash $ExpectedHash }`,
    `  return $dest`,
    `}`,
    ``,
    `function Install-Application {`,
    `  param([hashtable]$App)`,
    `  $name = $App.name`,
    `  if (Test-Installed -App $App) {`,
    `    Write-Log "Already installed: $name"`,
    `    return`,
    `  }`,
    `  Write-Log "Installing: $name"`,
    `  $method = $App.installMethod`,
    `  $localFile = Join-Path (Join-Path $ScriptDir "files") "$($App._bundleFileName)"`,
    `  try {`,
    `    if ($method -eq "EXE" -or $method -eq "PORTABLE") {`,
    `      $installer = Get-Installer -Name $name -LocalFile $localFile -Url $App.downloadUrl -ExpectedHash $App.sha256`,
    `      $args = $App.silentInstallCommand`,
    `      Start-Process -FilePath $installer -ArgumentList $args -Wait`,
    `    }`,
    `    elseif ($method -eq "MSI") {`,
    `      $msi = Get-Installer -Name $name -LocalFile $localFile -Url $App.downloadUrl -ExpectedHash $App.sha256`,
    `      Start-Process msiexec.exe -ArgumentList "/i", "\"$msi\"", "/qn", "/norestart" -Wait`,
    `    }`,
    `    elseif ($method -eq "ZIP") {`,
    `      $zip = Get-Installer -Name $name -LocalFile $localFile -Url $App.downloadUrl -ExpectedHash $App.sha256`,
    `      $dest = "$env:ProgramFiles\\$name"`,
    `      Expand-Archive -Path $zip -DestinationPath $dest -Force`,
    `    }`,
    `    elseif ($method -eq "WINGET") {`,
    `      $id = $App.silentInstallCommand`,
    `      Start-Process winget.exe -ArgumentList "install", "--id", $id, "--silent", "--accept-package-agreements", "--accept-source-agreements" -Wait`,
    `    }`,
    `    elseif ($method -eq "CHOCO") {`,
    `      $id = $App.silentInstallCommand`,
    `      Start-Process choco.exe -ArgumentList "install", $id, "-y" -Wait`,
    `    }`,
    `    if ($App.launchAfterInstall -and $App.launchArguments) {`,
    `      Start-Process $App.launchArguments -Wait:$false`,
    `    }`,
    `    New-Item -Path "HKLM:\\Software\\BootstrapHub\\Installed" -Force | Out-Null`,
    `    Set-ItemProperty -Path "HKLM:\\Software\\BootstrapHub\\Installed" -Name $App.id -Value (Get-Date -Format "o")`,
    `    Write-Log "Installed: $name"`,
    `  } catch {`,
    `    Write-ErrorLog "Failed to install $name\`: $_"`,
    `    throw`,
    `  }`,
    `}`,
    ``,
    `function Install-Extension {`,
    `  param([hashtable]$Ext)`,
    `  $browser = $Ext.browser`,
    `  $extId = $Ext.extensionId`,
    `  $policyPath = switch ($browser) {`,
    `    "CHROME" { "HKLM:\\Software\\Policies\\Google\\Chrome\\ExtensionInstallForcelist" }`,
    `    "BRAVE"  { "HKLM:\\Software\\Policies\\BraveSoftware\\Brave\\ExtensionInstallForcelist" }`,
    `    "EDGE"   { "HKLM:\\Software\\Policies\\Microsoft\\Edge\\ExtensionInstallForcelist" }`,
    `  }`,
    `  if (-not $policyPath) { return }`,
    `  New-Item -Path $policyPath -Force | Out-Null`,
    `  $existing = Get-ItemProperty -Path $policyPath -ErrorAction SilentlyContinue`,
    `  $next = 1`,
    `  for ($i = 1; $i -le 100; $i++) { if (-not $existing.PSObject.Properties["$i"]) { $next = $i; break } }`,
    `  Set-ItemProperty -Path $policyPath -Name "$next" -Value "$extId;$(if ($Ext.chromeStoreUrl) { $Ext.chromeStoreUrl } else { '' })"`,
    `  Write-Log "Configured extension policy for $browser\`: $extId"`,
    `}`,
    ``,
    `function Invoke-StartupAction {`,
    `  param([hashtable]$Action)`,
    `  if (-not $Action.enabled) { return }`,
    `  $type = $Action.actionType`,
    `  $target = $Action.target`,
    `  $wd = if ($Action.workingDir) { $Action.workingDir } else { $ScriptDir }`,
    `  Write-Log "Startup action: $($Action.name) [$type]"`,
    `  try {`,
    `    if ($type -eq "POWERSHELL") {`,
    `      Start-Process powershell.exe -ArgumentList "-ExecutionPolicy", "Bypass", "-Command", $target -WorkingDirectory $wd -Wait:$false`,
    `    }`,
    `    elseif ($type -eq "CMD") {`,
    `      Start-Process cmd.exe -ArgumentList "/c", $target -WorkingDirectory $wd -Wait:$false`,
    `    }`,
    `    elseif ($type -eq "EXECUTE") {`,
    `      $args = if ($Action.arguments) { $Action.arguments } else { "" }`,
    `      Start-Process $target -ArgumentList $args -WorkingDirectory $wd -Wait:$false`,
    `    }`,
    `    elseif ($type -eq "URL") {`,
    `      Start-Process $target -Wait:$false`,
    `    }`,
    `  } catch {`,
    `    Write-ErrorLog "Startup action failed $($Action.name)\`: $_"`,
    `  }`,
    `}`,
    ``,
    `# Main`,
    `Write-Log "Starting Bootstrap Hub installer for: ${escapePs1(manifest.name)}"`,
    ``,
    `if (-not $SkipSignatureCheck) {`,
    `  $sig = Get-Content $SignaturePath -Raw`,
    `  if ($sig -ne "${escapePs1(signature)}") {`,
    `    throw "Manifest signature mismatch. Use -SkipSignatureCheck to override."`,
    `  }`,
    `  Write-Log "Signature verified."`,
    `}`,
    ``,
    `$manifest = Get-Content $ManifestPath -Raw | ConvertFrom-Json`,
    ``,
    `foreach ($app in $manifest.applications) {`,
    `  Install-Application -App $app`,
    `}`,
    ``,
    `foreach ($ext in $manifest.extensions) {`,
    `  Install-Extension -Ext $ext`,
    `}`,
    ``,
    `foreach ($action in $manifest.startupActions | Sort-Object order) {`,
    `  Invoke-StartupAction -Action $action`,
    `}`,
    ``,
    `Write-Log "Bootstrap Hub installation complete."`,
  ];

  return lines.join("\r\n") + "\r\n";
}

function escapePs1(input: string): string {
  return input.replace(/`/g, "``").replace(/"/g, "`\"").replace(/\$/g, "`$");
}
